name 'chef-vault-demo-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-vault-demo-cookbook'
long_description 'Installs/Configures chef-vault-demo-cookbook'
version '0.1.0'
